apiVersion: v1 # Descriptor conforms to version v1 of Kubernetes API
kind: Pod # Select Pod resource
metadata:
  name: hello-kube # The name of the pod
  namespace: dev
spec:
  containers:
    - image: docker.io/library/hello-kube-1:latest # Image to create the container
      imagePullPolicy: IfNotPresent 
      name: hello-kube # The name of the container
      ports:
        - containerPort: 8081 # The port the app is listening on
          protocol: TCP