apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 2 # number of the pod
  selector: # The pod selector determining what pods the RC is operating on
    app: hello-kube # label value
  template: # pod template
    metadata:
      labels:
        app: hello-kube # label value
      # namespace: dev
    spec:
      containers:
      - image: docker.io/library/hello-kube-1:latest # image used to run container
        name: hello-kube # name of the container
        imagePullPolicy: IfNotPresent 
        ports:
          - containerPort: 8081 # pod of the container