version : "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 5000:5000
    container_name: jenkins
    volumes:
      - /Users/${myname}/Desktop/danhhuynh250/devops-learn/jenkins
      - /var/run/docker.sock:/var/run/docker.sock